name: "Setup Bun Environment"
description: "Setup Bun with caching for the funk-tree monorepo"

inputs:
  turbo-cache:
    description: "Enable Turborepo local caching"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version-file: package.json

    - name: Cache bun dependencies
      id: bun-cache
      uses: actions/cache@v4
      with:
        path: ~/.bun/install/cache
        key: ${{ runner.os }}-bun-${{ hashFiles('bun.lock') }}
        restore-keys: |
          ${{ runner.os }}-bun-

    - name: Cache Turborepo
      if: inputs.turbo-cache == 'true'
      uses: actions/cache@v4
      with:
        path: .turbo
        key: ${{ runner.os }}-turbo-${{ hashFiles('bun.lock') }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-turbo-${{ hashFiles('bun.lock') }}-
          ${{ runner.os }}-turbo-

    - name: Clear stale bun cache on partial restore
      if: steps.bun-cache.outputs.cache-hit != 'true'
      shell: bash
      run: rm -rf ~/.bun/install/cache

    - name: Install dependencies
      shell: bash
      run: bun install --frozen-lockfile
